### PR TITLE
Comment fix: right ndarray dimensions

### PR DESCRIPTION
**Pull request by ArchibaldArt**
io.loadmap() returns 'X' having shape (32, 32, 3, n_samples), not (3, 32, 32, n_samples).

### CODE REVIEW

**Review by sim0nsays — APPROVED** [review]
Thanks!

**Comment by sim0nsays** [comment]
Hold on, the comment is correct. The axis gets moved later

**Comment by ArchibaldArt** [comment]
io.loadmap() returns 'X' having shape (32, 32, 3, n_samples), not (3, 32, 32, n_samples).
Later axises updated to (n_samples, 32, 32, 3).

**Comment by sim0nsays** [comment]
Ah, ok, thanks!

**Pull request merged**
